### ISSUE TITLE
Dimension shift for second half?

### ISSUE THREAD

**Issue by Finnitio** [adamws/kicad-kbplacer#43]
I created a keyboard with ergogen
exported the points as yaml
converted the yaml to json
ran kbplacer script
imported the cutout.dxf from ergogen

Now there is a shift between left and right side points where the switches are placed.

**Screenshots**
![image](https://github.com/user-attachments/assets/82586927-c17b-4630-b340-dc7435d056ee)

KiCAD 8.0.5 release build
[files.zip](https://github.com/user-attachments/files/17821343/files.zip)

Edit screenshot is for a modified raw.dxf but shows the same shift betweens halfes.

**Comment by adamws** [comment]
I added following definition to your ergogen file:
```
pcbs:
  simple_pcb:
    footprints:
      keys:
        what: mx
        where: true
        params:
          from: "{{row_net}}"
          to: "{{column_net}}"
          keycaps: true
```
and compared PCB files (top: ergogen, bottom: kbplacer).
![spacing_difference](https://github.com/user-attachments/assets/300f57bc-8eaf-4ee1-8b27-e91fdf23649b)

looks like there is a problem with definition of 1U distance; If you want 19mm then change:
![image](https://github.com/user-attachments/assets/0b012361-35c1-441c-a863-6379e86e9904)
![image](https://github.com/user-attachments/assets/ba6c9425-9a3a-4fe6-9e0b-6dc5eeb586e3)
